- name: Stop kubelet and containerd
  service:
    name: "{{ item }}"
    state: stopped
  loop:
    - kubelet
    - containerd

- name: Run kubeadm reset and clean iptables
  shell: |
    kubeadm reset -f
    iptables -F
    iptables -t nat -F
    iptables -t mangle -F
    iptables -X
  args:
    executable: /bin/bash

- name: Kill any leftover kube/etcd processes
  shell: |
    pids=$(pgrep -f 'kube|etcd') || true
    if [ -n "$pids" ]; then
      kill -9 $pids
    fi
  args:
    executable: /bin/bash

- name: Remove Kubernetes and etcd data directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/kubernetes
    - /var/lib/etcd
    - /etc/cni/net.d
    - /var/lib/cni
    - /var/lib/kubelet
    - /root/.kube

- name: Start containerd again
  service:
    name: containerd
    state: started
