- name: Reset Kubernetes cluster
  shell: |
    kubeadm reset -f
    iptables -F
    iptables -t nat -F
    iptables -t mangle -F
    iptables -X
    rm -rf /etc/cni/net.d
    rm -rf ~/.kube
  args:
    executable: /bin/bash
