- name: Cài đặt containerd từ archive chính thức
  become: true
  vars:
    kube_bin_dir: /usr/local/bin
    cni_bin_dir: /opt/cni/bin
    kube_binaries:
      - kubeadm
      - kubelet
      - kubectl
  block:

    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ cni_bin_dir }}"
        - "{{ kube_bin_dir }}"
        - /usr/lib/systemd/system/kubelet.service.d

    - name: Download and extract CNI plugins
      unarchive:
        src: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-{{ arch }}-v{{ cni_plugins_version }}.tgz"
        dest: "{{ cni_bin_dir }}"
        remote_src: yes
        mode: '0755'

    - name: Download and extract crictl
      unarchive:
        src: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-{{ arch }}.tar.gz"
        dest: "{{ kube_bin_dir }}"
        remote_src: yes
        mode: '0755'

    - name: Download Kubernetes binaries {{ kubernetes_version }}
      get_url:
        url: "https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/{{ arch }}/{{ item }}"
        dest: "{{ kube_bin_dir }}/{{ item }}"
        mode: '0755'
      loop: "{{ kube_binaries }}"

    - name: Download and patch kubelet.service
      shell: |
        curl -sSL "https://raw.githubusercontent.com/kubernetes/release/v{{ kubelet_service_version }}/cmd/krel/templates/latest/kubelet/kubelet.service" |
        sed "s:/usr/bin:{{ kube_bin_dir }}:g" > /usr/lib/systemd/system/kubelet.service
      args:
        executable: /bin/bash

    - name: Download and patch kubelet drop-in config
      shell: |
        curl -sSL "https://raw.githubusercontent.com/kubernetes/release/v{{ kubelet_service_version }}/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf" |
        sed "s:/usr/bin:{{ kube_bin_dir }}:g" > /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
      args:
        executable: /bin/bash

    - name: Reload systemd and enable kubelet
      systemd:
        daemon_reload: yes
        name: kubelet
        enabled: yes
        state: started
