- name: Lấy IP đầu tiên (bỏ lo, bỏ 10.0.x.x)
  become: true
  shell: |
    ip -4 -o addr show | grep -v ' lo ' | awk '{print $4}' | cut -d/ -f1 | grep -vE '^10\.0\.' | head -n1
  register: node_ip_result
  changed_when: false
  failed_when: node_ip_result.stdout == ""

- name: Lấy danh sách EnvironmentFile của kubelet
  become: true
  shell: systemctl cat kubelet | grep -Po '(?<=EnvironmentFile=-)[^\s]+'
  register: kubelet_envfile_result
  changed_when: false

- name: Chọn file phù hợp để ghi --node-ip (ưu tiên /etc/sysconfig/kubelet)
  set_fact:
    kubelet_env_file: >-
      {{ kubelet_envfile_result.stdout_lines
         | select('search', '/etc/sysconfig/kubelet')
         | list | first
         if kubelet_envfile_result.stdout_lines
         | select('search', '/etc/sysconfig/kubelet')
         | list | length > 0
         else '/etc/sysconfig/kubelet' }}

- name: Ghi dòng cấu hình --node-ip vào {{ kubelet_env_file }}
  become: true
  lineinfile:
    path: "{{ kubelet_env_file }}"
    regexp: '^KUBELET_EXTRA_ARGS='
    line: "KUBELET_EXTRA_ARGS=--node-ip={{ node_ip_result.stdout }}"
    create: yes
    mode: '0644'

- name: Reload systemd và restart kubelet
  become: true
  systemd:
    name: kubelet
    daemon_reload: true
    state: restarted
