- name: Ensure Helm is installed
  shell: |
    if ! command -v helm &> /dev/null; then
      curl -sSL https://get.helm.sh/helm-v3.14.3-linux-amd64.tar.gz -o /tmp/helm.tar.gz
      tar -xzf /tmp/helm.tar.gz -C /tmp
      install /tmp/linux-amd64/helm /usr/local/bin/helm
    fi
  args:
    creates: /usr/local/bin/helm