- name: Cài đặt Vault bằng Helm chart (production-ready)
  become: true
  vars:
    vault_namespace: vault
    vault_release_name: vault
    vault_helm_chart: hashicorp/vault
    vault_helm_version: "0.28.0"
    vault_helm_values_file: /tmp/vault-values.yaml
    vault_storage_class: longhorn   # ← thay bằng "standard" nếu không dùng Longhorn
  block:

    - name: Gỡ cài đặt Vault bằng Helm
      shell: helm uninstall {{ vault_release_name }} -n {{ vault_namespace }}
      ignore_errors: true
      args:
        executable: /bin/bash

    - name: Xóa toàn bộ PVC trong namespace Vault
      shell: kubectl delete pvc --all -n {{ vault_namespace }}
      ignore_errors: true
      args:
        executable: /bin/bash

    - name: Tạo namespace nếu chưa tồn tại
      shell: |
        kubectl get ns {{ vault_namespace }} || kubectl create ns {{ vault_namespace }}
      args:
        executable: /bin/bash

    - name: Thêm Helm repo HashiCorp
      shell: helm repo add hashicorp https://helm.releases.hashicorp.com || true

    - name: Cập nhật Helm repo
      shell: helm repo update

    - name: Tạo file cấu hình values.yaml cho Vault (HA mode với Raft)
      copy:
        dest: "{{ vault_helm_values_file }}"
        content: |
          server:
            dev:
              enabled: false

            ha:
              enabled: true
              replicas: 3  # Should be at least 3 for production
              raft:
                enabled: true
                setNodeId: true
                config: |
                  storage "raft" {
                    path    = "/vault/data"
                  }

            standalone:
              enabled: false

            dataStorage:
              enabled: true
              storageClass: "{{ vault_storage_class }}"
              size: 8Gi

            haStorage:
              raft:
                enabled: true
                setNodeId: true

            extraEnvironmentVars:
              VAULT_LOG_LEVEL: debug

            readinessProbe:
              enabled: true
            livenessProbe:
              enabled: true

          ui:
            enabled: true

    - name: Cài đặt hoặc nâng cấp Vault bằng Helm
      shell: |
        helm upgrade --install {{ vault_release_name }} {{ vault_helm_chart }} \
          --namespace {{ vault_namespace }} \
          --version {{ vault_helm_version }} \
          -f {{ vault_helm_values_file }}
      args:
        executable: /bin/bash
