---
- name: Copy systemd unit
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 0644

- name: Reload systemd and enable etcd
  ansible.builtin.systemd:
    name: etcd
    enabled: true
    daemon_reload: true
    state: started
