- name: Install all components
  hosts: all
  become: true
  environment:
    KUBECONFIG: /home/namnv/.kube/config
  roles:
    - role: install_helm
    - role: longhorn
#    - role: vault
#    - role: cert-manager
#    - role: istio
#    - role: test
