---
- name: Cài đặt DevStack trên Ubuntu
  hosts: devstack
  become: true

  vars:
    devstack_user: stack
    host_ip: 10.148.0.41
    admin_pass: admin

  tasks:

    - name: Cài đặt gói phụ thuộc
      apt:
        name:
          - git
          - sudo
          - python3-pip
          - net-tools
          - curl
        update_cache: true

    - name: Tạo user stack
      user:
        name: "{{ devstack_user }}"
        home: "/opt/{{ devstack_user }}"
        shell: /bin/bash
        state: present
        create_home: true

    - name: Tạo thư mục home cho stack với quyền đúng
      file:
        path: "/opt/{{ devstack_user }}"
        state: directory
        owner: "{{ devstack_user }}"
        group: "{{ devstack_user }}"
        mode: '0755'

    - name: Cho phép stack sudo không cần mật khẩu
      copy:
        dest: "/etc/sudoers.d/{{ devstack_user }}"
        content: "{{ devstack_user }} ALL=(ALL) NOPASSWD: ALL\n"
        mode: '0440'

    - name: Clone DevStack repo as stack user (workaround)
      become: true
      shell: sudo -u stack git clone https://opendev.org/openstack/devstack.git /opt/stack/devstack
      args:
        creates: /opt/stack/devstack/.git


    - name: Tạo file local.conf (tạm với quyền root)
      copy:
        dest: "/opt/{{ devstack_user }}/devstack/local.conf"
        content: |
          [[local|localrc]]
          ADMIN_PASSWORD={{ admin_pass }}
          DATABASE_PASSWORD={{ admin_pass }}
          RABBIT_PASSWORD={{ admin_pass }}
          SERVICE_PASSWORD={{ admin_pass }}
          HOST_IP={{ host_ip }}
        mode: '0644'

    - name: Đổi chủ file local.conf thành stack
      file:
        path: "/opt/{{ devstack_user }}/devstack/local.conf"
        owner: "{{ devstack_user }}"
        group: "{{ devstack_user }}"

    - name: Chạy ./stack.sh dưới user stack (dùng sudo -u)
      shell: sudo -u stack ./stack.sh
      args:
        chdir: "/opt/{{ devstack_user }}/devstack"

