all:
  vars:
    ansible_user: namnv
    ansible_ssh_private_key_file: ~/.ssh/my_ecdsa_key
  children:
    master:
      hosts:
        master1:
          ansible_host: 192.168.56.10
          bootstrap: true
    worker:
      hosts:
        worker1:
          ansible_host: 192.168.56.12
