- name: Install Longhorn only on bootstrap node
  become: true
  vars:
    longhorn_namespace: longhorn-system
  block:
    - name: Ensure required packages are installed (Debian-based)
      shell: |
        sudo apt update
        sudo apt install -y open-iscsi nfs-common
        sudo systemctl enable --now iscsid
      args:
        executable: /bin/bash

    - name: Enable and start iscsid service
      service:
        name: iscsid
        enabled: yes
        state: started
    - block:
        - name: Ensure longhorn namespace exists
          shell: kubectl get ns {{ longhorn_namespace }} || kubectl create ns {{ longhorn_namespace }}

        - name: Add Longhorn Helm repo
          shell: |
            helm repo add longhorn https://charts.longhorn.io || true
            helm repo update

        - name: Install Longhorn via Helm
          shell: >
            helm upgrade --install longhorn longhorn/longhorn
            -n {{ longhorn_namespace }}
            --set persistence.defaultClassReplicaCount=1
            --set longhornUI.replicas=1

        - name: Expose Longhorn UI on NodePort 30080
          shell: >
            kubectl -n {{ longhorn_namespace }} patch svc longhorn-frontend \
              -p '{
                "spec": {
                  "type": "NodePort",
                  "ports": [{
                    "port": 80,
                    "targetPort": 8000,
                    "protocol": "TCP",
                    "nodePort": 30080
                  }]
                }
              }'


        - name: Set Longhorn as default StorageClass
          shell: >
            kubectl patch storageclass longhorn
            -p '{
                  "metadata": {
                    "annotations": {
                      "storageclass.kubernetes.io/is-default-class": "true"
                    }
                  }
                }'
