---
- name: Cài đặt DevStack trên Ubuntu
  hosts: devstack
  become: true

  vars:
    devstack_user: stack
    host_ip: 10.148.0.39
    admin_pass: admin

  tasks:

    - name: Cài đặt gói phụ thuộc
      apt:
        name:
          - git
          - sudo
          - python3-pip
          - net-tools
          - curl
        update_cache: true

    - name: Tạo user stack
      user:
        name: "{{ devstack_user }}"
        home: "/opt/{{ devstack_user }}"
        shell: /bin/bash
        state: present
        create_home: true

    - name: Tạo thư mục home cho stack với quyền đúng
      file:
        path: "/opt/{{ devstack_user }}"
        state: directory
        owner: "{{ devstack_user }}"
        group: "{{ devstack_user }}"
        mode: '0755'

    - name: Cho phép stack sudo không cần mật khẩu
      copy:
        dest: "/etc/sudoers.d/{{ devstack_user }}"
        content: "{{ devstack_user }} ALL=(ALL) NOPASSWD: ALL\n"
        mode: '0440'

    - name: Clone DevStack bằng become_user thật sự
      become_user: "{{ devstack_user }}"
      git:
        repo: https://opendev.org/openstack/devstack.git
        dest: "/opt/{{ devstack_user }}/devstack"


    - name: Tạo file local.conf (tạm với quyền root)
      copy:
        dest: "/opt/{{ devstack_user }}/devstack/local.conf"
        content: |
          [[local|localrc]]
          ADMIN_PASSWORD={{ admin_pass }}
          DATABASE_PASSWORD={{ admin_pass }}
          RABBIT_PASSWORD={{ admin_pass }}
          SERVICE_PASSWORD={{ admin_pass }}
          HOST_IP={{ host_ip }}
        mode: '0644'

    - name: Đổi chủ file local.conf thành stack
      file:
        path: "/opt/{{ devstack_user }}/devstack/local.conf"
        owner: "{{ devstack_user }}"
        group: "{{ devstack_user }}"

    - name: clean /opt/stack/async
      shell: sudo rm -f /opt/{{ devstack_user }}/async/*.fifo

    - name: Clone repo requirements nếu chưa tồn tại
      become_user: "{{ devstack_user }}"
      shell: |
        if [ ! -d /opt/{{ devstack_user }}/requirements ]; then
          git clone https://opendev.org/openstack/requirements.git /opt/{{ devstack_user }}/requirements
        fi

    - name: Fix quyền requirements
      file:
        path: "/opt/{{ devstack_user }}/requirements"
        owner: "{{ devstack_user }}"
        group: "{{ devstack_user }}"
        recurse: true


    - name: Chạy ./stack.sh dưới user stack (dùng sudo -u)
      shell: sudo -u {{ devstack_user }} bash -c "cd /opt/{{ devstack_user }}/devstack && ./stack.sh"
#sudo -u stack bash -c "cd /opt/stack/devstack && ./stack.sh"

