all:
  vars:
    ansible_user: namnv
    ansible_ssh_private_key_file: ~/.ssh/my_ecdsa_key
  children:
    master:
      hosts:
        master1:
          ansible_host: 34.124.237.41
          bootstrap: true
    worker:
      hosts:
        worker1:
          ansible_host: 35.197.146.206
