- name: Prepare all nodes (common setup, container runtime, kube)
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yml
  roles:
    - common
    - containerd
    - install_k8s
    - kube_ip

- name: Initialize only primary master
  hosts: master
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Init master (bootstrap only)
      include_role:
        name: init_master
      when: hostvars[inventory_hostname].bootstrap | default(false)

    - name: Setup CNI (bootstrap only)
      include_role:
        name: network
      when: hostvars[inventory_hostname].bootstrap | default(false)

    - name: Gen join file (bootstrap only)
      include_role:
        name: gen_file
      when: hostvars[inventory_hostname].bootstrap | default(false)

- name: Join other control-plane masters
  hosts: master
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Join control-plane
      include_role:
        name: join_master
      when: not hostvars[inventory_hostname].bootstrap | default(false)

- name: Join all workers
  hosts: worker
  become: true
  vars_files:
    - ../group_vars/all.yml
  roles:
    - join_worker
