arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
arch: "{{ arch_map[ansible_architecture] | default(ansible_architecture) }}"

# CIDR cho Pod network (dùng cho CNI plugin như Calico, Flannel, v.v.)
pod_network_cidr: 172.16.1.0/16

# IP nội bộ để kube-apiserver lắng nghe (phải tồn tại trên máy xem bằng `ip a`), nếu dùng GCP là Internal IP
apiserver_advertise_address: 10.148.0.35

# SANs cho chứng chỉ kube-apiserver (Internal IP + External IP)
apiserver_cert_sans:
  - 10.148.0.35
  - 34.124.237.41

cri_socket: "unix:///run/containerd/containerd.sock"


# install k8s
cni_plugins_version: 1.7.1 #https://github.com/containernetworking/plugins/releases
crictl_version: 1.31.0 #https://github.com/kubernetes-sigs/cri-tools/releases
kubelet_service_version: 0.18.0 #https://github.com/kubernetes/release/releases
kubernetes_version: 1.33.2  #https://cdn.dl.k8s.io/release/stable.txt

# install containerd
containerd_version: 2.1.3
opencontainers_runc_version: 1.3.0