- name: Cài đặt và cấu hình CRI-O
  become: true
  vars:
    crio_bin_path: "/usr/local/bin"
    crio_tar: "cri-o.{{ arch }}.{{ crio_version }}.tar.gz"
    crio_artifacts_url: "https://storage.googleapis.com/cri-o/artifacts/{{ crio_tar }}"
    crio_service_url: "https://raw.githubusercontent.com/cri-o/cri-o/{{ crio_version }}/contrib/systemd/crio.service"
    #cri_socket: "unix:///var/run/crio/crio.sock"
  block:

    - name: Tạo cấu trúc thư mục
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /usr/lib/systemd/system
        - /etc/crio
        - "{{ crio_bin_path }}"
        - /etc/containers

    - name: Tải và cài đặt CRI-O
      block:
        - name: Tải package CRI-O
          get_url:
            url: "{{ crio_artifacts_url }}"
            dest: "/tmp/{{ crio_tar }}"
            mode: '0644'

        - name: Giải nén và cài đặt
          unarchive:
            src: "/tmp/{{ crio_tar }}"
            dest: "/"
            remote_src: yes
            extra_opts: [ --no-overwrite-dir ]
            mode: '0755'

        - name: Cài đặt binaries
          command: cp -av /cri-o/bin/* "{{ crio_bin_path }}/"
          args:
            creates: "{{ crio_bin_path }}/crio"

    - name: Cấu hình CRI-O
      copy:
        dest: /etc/crio/crio.conf
        content: |
          [crio.runtime]
          conmon = "{{ crio_bin_path }}/conmon"
          default_runtime = "runc"
          
          [crio.runtime.runtimes.runc]
          runtime_path = "{{ crio_bin_path }}/runc"
          runtime_type = "oci"
        mode: '0644'

    - name: Cài đặt và cấu hình systemd service
      block:
        - name: Tải service file
          get_url:
            url: "{{ crio_service_url }}"
            dest: "/usr/lib/systemd/system/crio.service"
            mode: '0644'

        - name: Cập nhật đường dẫn binary
          replace:
            path: /usr/lib/systemd/system/crio.service
            regexp: '/usr/bin'
            replace: "{{ crio_bin_path }}"

    - name: Cấu hình container policy
      copy:
        dest: /etc/containers/policy.json
        content: |
          {
            "default": [{"type": "insecureAcceptAnything"}],
            "transports": {
              "docker": {
                "registry.k8s.io": [{"type": "insecureAcceptAnything"}]
              }
            }
          }
        mode: '0644'

    - name: Khởi động dịch vụ CRI-O
      systemd:
        name: crio
        enabled: yes
        state: started
        daemon_reload: yes